# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: davorg/centos-realperl
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        perl: [ 'latest' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
#      - name: Set up perl
#        uses: shogo82148/actions-setup-perl@v1
#        with:
#          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: yum install perl-App-cpanminus
      - run: cpanm --installdeps .
      - name: Archive CPAN logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cpan_log
          path: /home/runner/.cpanm/work/*/build.log
      - run: prove -lv t
